# Generated by Django 4.1.3 on 2022-11-20 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_image', models.ImageField(blank=True, max_length=40, upload_to='profileImages/')),
            ],
            options={
                'verbose_name': 'UProfiles',
                'verbose_name_plural': 'UProfiles',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='created_by', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('0', 'pending'), ('1', 'approved'), ('2', 'rejected'), ('3', 'undefined')], default='0', max_length=20)),
                ('seller_name', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('legal_seller_address', models.CharField(max_length=255)),
                ('contact_phone', models.PositiveSmallIntegerField()),
                ('seller_email', models.EmailField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
                'ordering': ('-creation_date',),
            },
        ),
    ]
