# Generated by Django 4.1.3 on 2022-11-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ushopping', '0003_alter_product_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-date',)},
        ),
    ]
